### PR TITLE
Redirect to 404 when workspace or dataset is not found

### LINKED ISSUE #807: Error pages to handle not having access to workspace or dataset page
## Context

Display a proper page when a user try to access a workspace he/she has not access to (or when the workspace/dataset slug is wrong.

The request access button is interesting in a second step

## Task

- [ ] Display the [404 screen](https://labelflow.ai/404) when
  - [ ] workspace/dataset slug does not exist
  - [ ] user has not access to workspace/dataset

### PR DESCRIPTION
**Pull request by Jordanlelay**
## Work performed

Redirect to 404 when workspace or dataset is not found

## Resolved issues

Closes #807

### CODE REVIEW

File: typescript/web/src/pages/[workspaceSlug]/datasets/[datasetSlug]/index.tsx [hunk 1]
```diff
@@ -30,6 +30,10 @@ const Body = () => {
     skip: typeof datasetSlug !== "string" || typeof workspaceSlug !== "string",
   });
 
+  if (error) {
+    router.push("/404");
+  }
```
Comment (bbenoist) [inline typescript/web/src/pages/[workspaceSlug]/datasets/[datasetSlug]/index.tsx:35]: Having an error with Apollo client does not necessarily means that the entity does not exists. We have to be more specific and keep the usual error handling when appropriate.

**Review by bbenoist — CHANGES_REQUESTED** [review]

File: typescript/web/src/pages/[workspaceSlug]/datasets/[datasetSlug]/index.tsx (hunk 1 above)
Comment (Jordanlelay) [reply typescript/web/src/pages/[workspaceSlug]/datasets/[datasetSlug]/index.tsx:35]: What is the usual error handling ?

Comment (bbenoist) [reply typescript/web/src/pages/[workspaceSlug]/datasets/[datasetSlug]/index.tsx:35]: Rely on `typescript/web/src/pages/_error.tsx` IIRC

File: typescript/web/src/pages/[workspaceSlug]/datasets/[datasetSlug]/index.tsx [hunk 2]
```diff
@@ -30,6 +31,16 @@ const Body = () => {
     skip: typeof datasetSlug !== "string" || typeof workspaceSlug !== "string",
   });
 
+  if (
+    error &&
+    !isNil(error.networkError) &&
+    "result" in error.networkError &&
+    error.networkError.result.errors[0].message ===
+      "User not authorized to access dataset"
```
Comment (bbenoist) [inline typescript/web/src/pages/[workspaceSlug]/datasets/[datasetSlug]/index.tsx:39]: As with #964 , please use `getApolloErrorMessage` so that the code is smaller and safer.

**Review by bbenoist — CHANGES_REQUESTED** [review]

**Review by bbenoist — APPROVED** [review]
