### PR TITLE
Bug/#578 fix online export

### LINKED ISSUE #578: Export does not work on online workspaces
**Describe the bug**
Export does not work on online workspaces

**To Reproduce**
- [x] Export to COCO with or without images does not work. query `exportDatasetUrl` fails with error: 
```
errors: [{message: "btoa is not defined", locations: [{line: 2, column: 3}], path: ["exportDataset"]}]
```

- [x] Export to YOLO with or without images does not work. query `exportDatasetUrl` fails with error: 
```
{"errors":[{"message":"blob is not supported by this platform","locations":[{"line":2,"column":3}],"path":["exportDataset"]}],"data":null}
```

### PR DESCRIPTION
**Pull request by etiennedupont**
# Feature

## Resolved issues

Closes #578

### CODE REVIEW

File: typescript/common-resolvers/src/export/format-coco/json-to-data-uri.ts [hunk 1]
```diff
@@ -1,5 +1,25 @@
...
+    return Buffer.from(b64Encoded, "base64").toString("binary");
+  }
+};
+
 export const jsonToDataUri = (json: string): string =>
-  `data:application/json;base64,${btoa(json)}`;
+  `data:application/json;base64,${universalBtoa(json)}`;
+// `data:application/json;base64,${Buffer.from(json, "binary").toString(
+//   "base64"
+// )}`;
```
Comment (RaynalHugo) [inline typescript/common-resolvers/src/export/format-coco/json-to-data-uri.ts:21]:
```suggestion
  `data:application/json;base64,${universalBtoa(json)}`;
```

File: typescript/common-resolvers/src/export/format-coco/json-to-data-uri.ts [hunk 2]
```diff
@@ -1,5 +1,25 @@
...
 
 export const dataUriToJson = (dataUri: string): string =>
-  atob(dataUri.split(",")[1]);
+  universalAtob(dataUri.split(",")[1]);
+// Buffer.from(dataUri.split(",")[1], "base64").toString("binary");
```
Comment (RaynalHugo) [inline typescript/common-resolvers/src/export/format-coco/json-to-data-uri.ts:25]:
```suggestion
  universalAtob(dataUri.split(",")[1]);
```

File: typescript/common-resolvers/src/export/format-yolo/export-to-yolo.ts [hunk 3]
```diff
@@ -1,4 +1,5 @@
 import { ExportOptionsYolo, LabelType } from "@labelflow/graphql-types";
+// import { Blob } from "buffer";
 import JSZip from "jszip";
```
Comment (RaynalHugo) [inline typescript/common-resolvers/src/export/format-yolo/export-to-yolo.ts:3]:
```suggestion
import { ExportOptionsYolo, LabelType } from "@labelflow/graphql-types";
import JSZip from "jszip";
```

**Review by RaynalHugo — APPROVED** [review]
Tested on the deployed version, it works 👏 

I've just submitted a few suggestions to remove some comments.
