### PR TITLE
Bug/#469 cannot rename dataset

### LINKED ISSUE #469: Cannot rename a dataset
**Describe the bug**
Cannot rename a dataset

**To Reproduce**

1. Create a dataset
2. Try to rename it
3. Error: `This name is already taken`

**Expected behavior**
Possibility to rename a dataset

**Tasks**

- [ ] Solve bug
- [ ] Add end-to-end tests to check this feature is not broken by future changes.

**Screenshots**
image

**Additional context**

### PR DESCRIPTION
**Pull request by etiennedupont**
# Feature

## Work performed

- Fixed bug when renaming dataset
- Added one suite of end-to-end tests for dataset creation, renaming, deletion

## Resolved issues

Closes #469

### CODE REVIEW

File: typescript/web/src/components/datasets/upsert-dataset-modal.tsx [hunk 1]
```diff
@@ -136,7 +136,7 @@ export const UpsertDatasetModal = ({
 
   useEffect(() => {
     if (
-      existingDataset != null &&
+      existingDataset?.searchDataset != null &&
```
Comment (nacho-carnicero) [inline typescript/web/src/components/datasets/upsert-dataset-modal.tsx:139]: Maybe we should check here that `existingDataset?.searchDataset?.id != null` as it is the property that we are comparing to the current datased ID later on?

Comment (crubier) [reply typescript/web/src/components/datasets/upsert-dataset-modal.tsx:139]:
```suggestion
      existingDataset?.searchDataset?.id != null &&
```
