### PR TITLE
Bug/#360 cant modify invalid geometry

### LINKED ISSUE #360: Cant modify invalid geometry
**Describe the bug**

Cant modify invalid geometry

Error Updating Label: Each LinearRing of a Polygon must have 4 or more Positions.

**To Reproduce**
1. Create an invalid geometry
2. Try to modify it

Screenshot 2021-08-18 at 22 20 27

**Solution**

- [ ] Correct the function making invalid geometries valid ([check that line](https://github.com/Labelflow/labelflow/blob/55088873d875c156e9ee14f31e38ef72dd77477d/typescript/common-resolvers/src/utils/get-bounded-geometry-from-image.ts#L11))

### PR DESCRIPTION
**Pull request by etiennedupont**
# Feature

## Work performed

- Use `MultiPolygon` instead of `Polygon` when creating polygons
- Handle MultiPolygon in `Coco export`

## Resolved issues

Closes #360

### CODE REVIEW

File: typescript/common-resolvers/src/format-coco/coco-core/converters.ts [hunk 1]
```diff
@@ -67,6 +71,36 @@ const convertLabelClassesToCocoCategories = (labelClasses: DbLabelClass[]) => {
...
+  return geomReduce(
+    flatten(geometry),
+    (segmentations: number[][], currentGeometry) => [
+      ...segmentations,
+      coordReduce(currentGeometry, coordToSegmentationReducer, []),
+    ],
+    []
+  );
+};
+
```
Comment (etiennedupont) [inline typescript/common-resolvers/src/format-coco/coco-core/converters.ts:103]: Since we know that we're manipulating only MultiPolygons, I was wondering whether we could avoid using `flatten`, `geomReduce`, `coordReduce` by just making a reduce in `geometry.coordinates`, and keeping the first linear ring for each polygon.

Comment (crubier) [reply typescript/common-resolvers/src/format-coco/coco-core/converters.ts:103]: I'd prefer to keep some geometry-agnostic code with `geomReduce` and others, it's a better practice I feel.

Comment (etiennedupont) [reply typescript/common-resolvers/src/format-coco/coco-core/converters.ts:103]: I agree, still, is `flatten` strictly required l95 @ShauniArima ? Since I see `_multiFeatureIndex` l83 which makes me think that a multipolygon would be iterated on each enclosed polygon?
