### PR TITLE
Fix timeout on label export

### LINKED ISSUE #844: Export labels: fix timeout on COCO and YOLO json export
## Tasks
- Log why there is a timeout on a medium size dataset
- Try to use Prisma relation to batch every DB call in a single query

### Yolo:
- For every image, it queries the list of LabelClasses
- Action batch the LabelClasses of a dataset

### Coco:
- For every label, it queries the image dimensions
- Action: query the image dimension only once

### PR DESCRIPTION
**Pull request by Jordanlelay**
## Work performed

- Rework the way labels are exported
- Remove unused flickr_url

## Results

The labels, labelClasses and images of a dataset are now queried once for all at the beginning of the export procedure. A temporary object is built for fast access when iterating over the labels / images.

Tests I've conducted over a 11000+ labels dataset:
- yolo export -> From ~20s to ~10s
- coco export -> From `timeout` to ~8s

## Caveats

The tests were **only** focusing on labels and not images. If too much timeouts because of images happen, there is another way we could potentially improve performances:

- In both COCO and YOLO exports, for each image, this query is executed: `await repository.upload.get(image.url, req);`, returning an `ArrayBuffer` of the to-be-exported image. We could potentially batch these calls as we already have the full list of the dataset's images.

## Resolved issues

Closes #844

### CODE REVIEW

File: typescript/common-resolvers/src/export/format-yolo/export-to-yolo.ts [hunk 1]
```diff
@@ -6,6 +6,19 @@ import { getImageName } from "../common";
...
+        const key = label.imageId;
+        if (!acc[key]) {
+          acc[key] = [];
+        }
+        acc[key].push(label);
+        return acc;
+      }, {})
+    : {};
+};
+
```
Comment (bbenoist) [inline typescript/common-resolvers/src/export/format-yolo/export-to-yolo.ts:21]: You can use [lodash groupBy](https://lodash.com/docs/#groupBy) function to do this operation.
I guess you'd end-up with something like:

```suggestion
import { isEmpty, groupBy } from "lodash/fp";
import { ExportFunction } from "../types";

const groupLabelsByImage = (labels: DbLabel[]) =>
  isEmpty(labels) ? {} : groupBy(labels, "imageId");
```

File: typescript/common-resolvers/src/export/format-coco/add-image-dimensions-to-labels.ts [hunk 2]
```diff
@@ -1,22 +1,28 @@
-import { DbLabel, Repository } from "../../types";
-import { DbLabelWithImageDimensions } from "./coco-core/types";
+import { DbImage } from "../..";
+import { DbLabel } from "../../types";
 
-export const addImageDimensionsToLabels = async (
+type ImageDimensions = {
```
Comment (bbenoist) [inline typescript/common-resolvers/src/export/format-coco/add-image-dimensions-to-labels.ts:4]: If you're OK, let's rename and move the type into a `geometry` directory of @labelflow/utils. We will populate the directory with all geometry-related types and functions and eventually switch easier to a dedicated library if it becomes too big..
No need to make sure it's used everywhere for now but it will let us reuse it anywhere a 2D size is needed 🚀 

```suggestion
export type Size2D = {
```

File: typescript/common-resolvers/src/export/format-coco/add-image-dimensions-to-labels.ts [hunk 3]
```diff
@@ -1,22 +1,28 @@
...
-      if (image == null) {
-        throw new Error(`Missing image with id ${imageId}`);
+  images: DbImage[]
+) => {
+  const dimensionsByImage = images.reduce(
+    (acc: { [imageId: string]: ImageDimensions }, image) => {
+      const key = image.id;
+      if (!acc[key]) {
+        acc[key] = { width: image.width, height: image.height };
       }
```
Comment (bbenoist) [inline typescript/common-resolvers/src/export/format-coco/add-image-dimensions-to-labels.ts:18]:
```suggestion
  const dimensionsByImage = images.reduce<Record<string, Size2D>>(
    (prev, { id, width, height }) => ({ ...prev, [id]: { width, height }}),
    {},
  );
```

File: typescript/common-resolvers/src/export/format-coco/add-image-dimensions-to-labels.ts [hunk 4]
```diff
@@ -1,22 +1,28 @@
...
-      return {
-        ...label,
-        imageDimensions: { height: image.height, width: image.width },
-      };
-    })
+      return acc;
+    },
+    {}
   );
```
Comment (bbenoist) [inline typescript/common-resolvers/src/export/format-coco/add-image-dimensions-to-labels.ts:22]:
```suggestion
```

File: typescript/common-resolvers/src/export/format-coco/add-image-dimensions-to-labels.ts [hunk 5]
```diff
@@ -1,22 +1,28 @@
...
+
```
Comment (bbenoist) [inline typescript/common-resolvers/src/export/format-coco/add-image-dimensions-to-labels.ts:23]:
```suggestion
```

**Review by bbenoist — CHANGES_REQUESTED** [review]

**Comment by bbenoist** [comment]
I've made a review but it'd like @valerian to give it a look too.

**Comment by nicOwlas** [comment]
I can see the improvement on the Georgia test dataset. It's much faster to export 👍

File: typescript/common-resolvers/src/export/format-coco/add-image-dimensions-to-labels.ts (hunk 2 above)
Comment (Jordanlelay) [reply typescript/common-resolvers/src/export/format-coco/add-image-dimensions-to-labels.ts:3]: Actually it's a small part of the `DbImage` type so maybe I could just `Pick` from it to reflect that it doesn't come out of nowhere

Comment (bbenoist) [reply typescript/common-resolvers/src/export/format-coco/add-image-dimensions-to-labels.ts:3]: Yes, let's pick the type for now, it's simpler 👍

**Review by bbenoist — APPROVED** [review]
